version: "3.2"

services:
  my-mondoDB:
    container_name: my-mondoDB
    image: 'mongo:latest'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: